#!/bin/bash

# Function to calculate CPU usage
cpu() {
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a + b + c + previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a + b + c + idle))
  cpu=$((100 * ((total - prevtotal) - (idle - previdle)) / (total - prevtotal)))
  echo -e "$cpu%"
}

# Function to get RAM usage
mem() {
  mem="$(free -h | awk '/^Mem/ { print $3 }' | sed 's/i//g')"
  echo -e "$mem"
}

# Function to get disk usage
hdd() {
  hdd="$(df -h --output=used,pcent / | tail -1)"
  echo -e "$hdd"
}

# Function to get CPU temperature
temp() {
  TEMP="$(sensors | awk 'BEGIN {i = 0; t = 0} /Core/ {++i; t += $3} END {if (i > 0) {printf "%0.1f°C", t / i}}')"
  echo -e "$TEMP"
}

# Function to get battery status
power() {
  PWR=$(cat /sys/class/power_supply/BAT0/capacity)
  echo -e "$PWR%"
}

# Function to get audio volume and mute status
volume() {
  volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1)
  muted=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -o 'yes\|no')
  if [ "$muted" = "yes" ]; then
    echo "🔇 Muted"
  else
    echo "🔊 $volume"
  fi
}

# Function to get screen brightness
brightness() {
  brightness=$(cat /sys/class/backlight/*/brightness)
  max_brightness=$(cat /sys/class/backlight/*/max_brightness)
  percent=$((100 * brightness / max_brightness))
  echo -e "$percent%"
}

# Function to get the current date and time
clock() {
  dte="$(date +"%a, %B %d %I:%M %p" | sed 's/  / /g')"
  echo -e "$dte"
}

# Infinite loop to update the dwm status bar
while true; do
  xsetroot -name "   $(cpu)   |   $(mem)   |   $(hdd)   |   $(power)   |   $(temp)   |  $(volume)   |   $(brightness)   |  $(clock) "
  sleep 5s
done &

